### ISSUE TITLE
获取原始数据报错

### ISSUE THREAD

**Issue by zhangdongdong7** [XWJR-Ops/Splunk-WeChat-Alert#3]
获取原始数据的时候，报错
![图片](https://user-images.githubusercontent.com/40697450/81544186-bd207b00-93a9-11ea-9fa6-804dc11ded53.png)

**Comment by zhangdongdong7** [comment]
[root@ops-rancher-jumpserver-splunk scripts]# python splunk_weixin.py 
Traceback (most recent call last):
  File "splunk_weixin.py", line 35, in <module>
    gzip_file = sys.argv[8]
IndexError: list index out of range

**Comment by X-Mars** [comment]
close
